steps:
- task: UseRubyVersion@0
  inputs:
    versionSpec: '>= 2.5'

- task: CacheBeta@1
  inputs:
    key: $(CACHE_KEY)
    path: $(BUNDLE_PATH)
    cacheHitVar: CACHE_RESTORED
  displayName: Cache gems

- task: Cache@2
  inputs:
    key: $(CACHE_KEY) | cachega
    path: $(BUNDLE_PATH)
  displayName: Cache gems GA

#- script: bundle install
#  displayName : "bundle install"
#  condition: ne(variables.CACHE_RESTORED, 'true')

- script: |
    gem install bundler
    bundle install --retry=3 --jobs=4
  displayName: 'bundle install'
  condition: ne(variables.CACHE_RESTORED, 'true')

- script: gem list

- script: bundle exec rake
  displayName: 'bundle exec rake'

# - script: bundle exec rspec spec --format RspecJunitFormatter --out test_results/TEST-rspec.xml

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFiles: '**/test-*.xml'
    testRunTitle: 'Ruby tests'
    
- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)/**/coverage'