trigger:
- master
jobs:
- job: publishhh
  pool:
    vmImage: $(myVmImage)
  steps:
  - script: |  
     cd $(Build.ArtifactStagingDirectory)
     echo "hello world" > hi.txt
     echo "bye" > bye.txt
     mkdir usa
     cd usa
     mkdir nc
     cd nc
     mkdir durham
     cd durham
     echo "hello from Durham" > greeting.txt

    displayName: Create some text files
  - task: PublishBuildArtifacts@1
    displayName: "Publish Artifact: drop"
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: drop
      publishLocation: Container
- job: downloaddd
  dependsOn: publishhh
  condition: succeeded()
  pool:
    vmImage: $(myVmImage)
  steps:
  - task: DownloadBuildArtifacts@0
    displayName: "Download Build Artifacts"
    inputs:
      artifactName: drop
